include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_const_constructors: true
    avoid_print: true
    cancel_subscriptions: true
    unawaited_futures: true

analyzer:
  exclude:
    - build/**
    - android/**
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
